### ISSUE TITLE
Username and password are clunky to retrieve

### ISSUE THREAD

**Issue by arichtman** [harleylang/hydroxide-docker#12]
When the container first authenticates the username and password for IMAP/SMTP authentication are printed to stdout as human-friendly text. This is not only clunky to retrieve but annoying to work with programmatically. A method to produce something serialised or structured (e.g. JSON or YAML) would make it easier to retrieve. More systemically there must be a better way of exposing or passing this information to the user.

**Comment by harleylang** [comment]
Closed. See: https://github.com/harleylang/hydroxide-docker/pull/20#issuecomment-1002132390
