### ISSUE TITLE
Thunderbird not connecting to Hydroxide

### ISSUE THREAD

**Issue by danielriddell21** [harleylang/hydroxide-docker#16]
Hi, I am running my hydroxide in my docker for windows w/ WSL 2.0. (This means it connects to a linux distro running on windows)

running 'docker run' with the ports 1025 and 1145, I try to connect with thunderbird but it never connects when i run test, 
I have tried localhost, as well as the direct docker container ip. I have tried with branches: `master` and `arichtman:ft-2fa`

**Incoming**
> Protocol: IMAP
> Sever: localhost
> Port: 1143
> SSL: None
> Authentication: Normal Password
> Username: email without the @protonmail.com

**Outgoing**
> Protocol: IMAP
> Sever: localhost
> Port: 1025
> SSL: None
> Authentication: Normal Password
> Username: email without the @protonmail.com

![image](https://user-images.githubusercontent.com/25375432/107986294-b02d5980-6fc3-11eb-92ee-600faac25c77.png)

**Comment by harleylang** [comment]
Thanks @bobland1 for your report!

Let's debug on the master branch for now, as `arichtman:ft-2fa` is still in review.

Can you run `send_mail.py` and let me know if it effectively sends a test message?

**Comment by danielriddell21** [comment]
Yeah sure, yeah send_mail.py works fine. Seems to be an issue trying to connect to the IMAP / SMTP outside of the docker container

**Comment by harleylang** [comment]
Gotcha. OK a few follow-up questions:

1) Have you exposed both those ports in the Dockerfile?

https://github.com/harleylang/hydroxide-docker/blob/f19ea54da6c7f323d104980e837ab68f26327aff/hydroxide/Dockerfile#L40

2) Forgive me, I'm on a linux system so my knowledge of Windows Subsystem is limited and this next question might be a shot in the dark. Is your `docker-machine ip` different from local host? See:
* https://github.com/docker/for-win/issues/204#issuecomment-604617284
* https://github.com/microsoft/WSL/issues/4983#issuecomment-602487077

**Comment by agates** [comment]
Been watching this issue, forgive my random interruption.  WSL 2 runs in hyper-v with NAT.  You need to add a port forward on the network adapter and possibly add a firewall rule.

https://github.com/microsoft/WSL/issues/4150

**Comment by danielriddell21** [comment]
Adding a firewall rule fixed my issue thank you

**Comment by harleylang** [comment]
That's great news, thanks again @bobland1 for submitting the issue and reporting back with the fix, and big shout out to @agates for sharing the wisdom of setting the firewall :fire: much appreciated!
