### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by mtompkins** [harleylang/hydroxide-docker#17]
Builds recently started failing. I did try to see if I could find any directory change, but couldn't isolate the cause.
Error:

```
Step 4/14 : RUN git -C ./src/ clone https://github.com/emersion/hydroxide/
 ---> Running in 192dd21d1b0e
Cloning into 'hydroxide'...
Removing intermediate container 192dd21d1b0e
 ---> 07af5fa91a0a
Step 5/14 : RUN go get -d ./src/hydroxide/cmd/hydroxide/...
 ---> Running in 35e8943576d0
go: cannot find main module; see 'go help modules'
The command '/bin/sh -c go get -d ./src/hydroxide/cmd/hydroxide/...' returned a non-zero code: 1
```

**Comment by harleylang** [comment]
Thanks @mtompkins for reporting! This looks like a similar issue to #2. I have pushed a commit and tested locally. Looks like it works on my end. Please pull the latest commit and let me know if the patch fixes your build.

Commit: 46861aaf0f6096e816f3c83813c22b29a206eb63

**Comment by mtompkins** [comment]
@harleylang confirmed that the change resolves the build issue. Thanks for your work.

**Comment by harleylang** [comment]
No problem!!
