### ISSUE TITLE
Getting Bridge Password?

### ISSUE THREAD

**Issue by DiscordiaMatrix** [harleylang/hydroxide-docker#18]
I am new to docker, and I am having a very hard time figuring out how to get the bridge password that is created when hydroxide first logs in. I tried docker log, but that didn't show that output. 

Is there a specific command I can run when doing docker-compose to re-create the container that will have hydroxide show me the output? Or is there a better method?

**Comment by harleylang** [comment]
Hi @DiscordiaChaos :wave: 

Once the container is running, you should find the bridge password at `/opt/hydroxide-container/data-hydroxide/info.json`

The file should contain the following data:

```
{
	'user': 'you@yourwebsite.com',
	'hash': 'yourhyDrOxIdEhaShHerE' // <---- for example sake, it will look different of course
}
```

On your local system, you can draw this information from that folder to make a SMTP call on the same port as your hydroxide container.

Are you familiar with python? If so, the `send_mail.py` file provides an example of how to access that file and send a test message.

Does that help answer your question?

**Comment by DiscordiaMatrix** [comment]
Thank you, that does help.

I did try the send_mail.py just now but I saw this error (emails replaced below as to not expose them)
```
root@www:~/hydroxide-docker-master# python send_mail.py
Traceback (most recent call last):
  File "send_mail.py", line 115, in <module>
    example()
  File "send_mail.py", line 104, in example
    send('SENDER','RECEIVER','Test message','This is a test message to verify that this script is working accordingly.')
  File "send_mail.py", line 72, in send
    mailserver.login(account, password)
  File "/usr/lib/python2.7/smtplib.py", line 623, in login
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (454, '4.7.0 Invalid username or password')

```

I will try to completely redo the container fresh and see if it helps. The login and password _should_ be correct, but I'll make 100% sure of it when redoing it.

**Comment by harleylang** [comment]
Gotcha! Yes, try cloning the repository again. Carefully enter your password into the docker config, and let me know if you see the same error.

**Comment by DiscordiaMatrix** [comment]
Alright, so I downloaded it fresh and everything,  but it's still saying this on the send_mail.py:
```
 File "/usr/lib/python2.7/smtplib.py", line 623, in login
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (454, '4.7.0 Invalid username or password')
```
I checked in that account's authentication logs and it shows the login was successful from the server's IP address. Should I open a different ticket to debug that?

**Comment by DiscordiaMatrix** [comment]
Oh it was User Error! I ran `docker run -it -p 1025:1025 -v /opt/hydroxide-container/data-hydroxide:/data hydroxide` and the docker-compose command after... no wonder I was having issues. Thank you for your help. :)

**Comment by harleylang** [comment]
Thanks for reporting back @DiscordiaChaos, that's great news that it worked out!
