### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by mtompkins** [harleylang/hydroxide-docker#19]
It looks like it might be from the `emersion/hydroxide/` source, however as I'm not a Go guy sharing the current status ...

```
...
go: downloading github.com/emersion/go-bcrypt v0.0.0-20170822072041-6e724a1baa63
go: downloading github.com/emersion/go-sasl v0.0.0-20200509203442-7bfe0ed36a21
go: downloading github.com/boltdb/bolt v1.3.1
go: downloading github.com/emersion/go-textwrapper v0.0.0-20200911093747-65d896831594
go: downloading github.com/martinlindhe/base36 v1.1.0
go: downloading golang.org/x/text v0.3.5-0.20201125200606-c27b9fd57aec
/go/pkg/mod/github.com/emersion/go-bcrypt@v0.0.0-20170822072041-6e724a1baa63/bcrypt.go:18:2: missing go.sum entry for module providing package golang.org/x/crypto/blowfish (imported by github.com/emersion/go-bcrypt); to add:
        go get github.com/emersion/go-bcrypt@v0.0.0-20170822072041-6e724a1baa63
/go/pkg/mod/github.com/howeyc/gopass@v0.0.0-20190910152052-7cb4b85ec19c/terminal.go:21:8: missing go.sum entry for module providing package golang.org/x/crypto/ssh/terminal (imported by github.com/howeyc/gopass); to add:
        go get github.com/howeyc/gopass@v0.0.0-20190910152052-7cb4b85ec19c
The command '/bin/sh -c cd /go/src/hydroxide/cmd/hydroxide && go build . && go install . && cd' returned a non-zero code: 1
```

**Comment by harleylang** [comment]
Thanks @mtompkins for reporting!

I think I have identified what has happened:

1) Looks like dependencies for hydroxide recently changes: https://github.com/emersion/hydroxide/commit/0df2e43d8ddfedc09183b5b5fc02ccfa2a2dc422#diff-f5c9a39fac1719f2a73593994b931d8a874449548e8a3753e1be46e761e503ea

2) Another dependency `github.com/emersion/go-bcrypt` (as well as `github.com/howeyc/gopass`) require imports that are no longer provided by `golang.org/x/crypto/bcrypt`: see https://github.com/emersion/go-bcrypt/blob/6e724a1baa633595ee7629cc82f284f8a5fcb10a/bcrypt.go#L18
     * For the above line, that line should be changed to `github.com/ProtonMail/go-crypto/bcrypt`, at least as best as I can sus atm.

>EDIT: yes, looks like this is a result of the commit above: see https://builds.sr.ht/~emersion/job/480522

Can you report on the main repository? For now, let's keep this open in case others run into a similar build issue.

**Comment by mtompkins** [comment]
Resolved upstream
