### ISSUE TITLE
Unable to send or save drafts

### ISSUE THREAD

**Issue by arichtman** [harleylang/hydroxide-docker#6]
For investigation - all using Thunderbird. Fix may simply be to not use Thunderbird.

On save to drafts: `2020/12/26 11:15:59 request failed: POST https://mail.protonmail.com/api/messages: [2000] The Sender is required`

On attempt send: `2020/12/26 11:14:45 creating draft message
2020/12/26 11:14:45 request failed: POST https://mail.protonmail.com/api/messages: [2001] Invalid sender`

**Comment by harleylang** [comment]
Closed. See: https://github.com/harleylang/hydroxide-docker/pull/20#issuecomment-1002132390
