### ISSUE TITLE
Accesstoken in the build phase?

### ISSUE THREAD

**Issue by arichtman** [harleylang/hydroxide-docker#9]
Consider authenticating and generating the `accesstoken ` in the build phase? Would still mean baking the access token into the eventual image but would remove the password from ever being present. Note that this would mean the workflow/usage would preclude ever publishing the image to a publically accessible registry (well, one without access controls).

**Comment by harleylang** [comment]
Closed. See: https://github.com/harleylang/hydroxide-docker/pull/20#issuecomment-1002132390
